--liquibase formatted sql
--changeset ach:1
DROP TABLE IF EXISTS BOOKINGS;
CREATE TABLE BOOKINGS
(
    ID             UUID    NOT NULL,
    OWNER_ID       UUID,
    TENANT_ID      UUID,
    APARTMENT_ID   UUID,
    CHECK_IN_DATE  DATE,
    CHECK_OUT_DATE DATE,
    PRICE          integer NOT NULL,
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS APARTMENTS;
create table APARTMENTS
(
    ID            UUID    NOT NULL,
    NAME          VARCHAR(255),
    PRICE_FOR_DAY INTEGER NOT NULL,
    DESCRIPTION   VARCHAR(255),
    SURFACE       DOUBLE  NOT NULL,
    OWNER_ID      UUID    NOT NULL,
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS OWNERS;
CREATE TABLE OWNERS
(
    ID   UUID NOT NULL,
    NAME VARCHAR(255),
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS TENANTS;
create table TENANTS
(
    ID   UUID NOT NULL,
    NAME VARCHAR(255),
    PRIMARY KEY (ID)
);

alter TABLE BOOKINGS
    add CONSTRAINT FKDW0XFNNTHBJ8AFP1IRA6SNDWQ
        foreign key (OWNER_ID) references OWNERS (ID);
alter table BOOKINGS
    add CONSTRAINT FKDW0XFNNTHBJ8AFP1IRA6SNDV
        foreign key (APARTMENT_ID) references APARTMENTS (ID);
alter table BOOKINGS
    add CONSTRAINT FKDW0XFNNTHBJ8AFP1IRA6SNDG
        foreign key (TENANT_ID) references TENANTS (ID);
alter table APARTMENTS
    add CONSTRAINT FKDW0XFNNTHBJ8AFP1IRA6SNDS
        foreign key (OWNER_ID) references OWNERS (ID);